version: '3.8'
services:
  backend:
    build:
      context: ./src
    networks:
      - web_net
    ports:
      - "8000:8000"
    depends_on:
      - db
    # volumes:
    #   - ./files/uploaded:/backend/files/uploaded
  
  db:
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    image: "postgres:latest"
    networks:
      - web_net
    ports: 
      - "5432:5432"
  
networks:
  web_net:
      driver: bridge