version: '3.8'
services:
  backend:
    build:
      context: ./src
    networks:
      - web_net
    ports:
      - "8000:8000"
    depends_on:
      - db
    
  db:
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'db'
    image: "postgres:latest"
    networks:
      - web_net
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "kevingamez.kg@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "5050:80"


networks:
  web_net:
    driver: bridge
